version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge