name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Create project directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -v ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p /home/ubuntu/flexlab'
        
    - name: Copy files to EC2 excluding virtual environment
      run: |
        rsync -avz --exclude 'myenv' --exclude 'venv' --exclude '.git' . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/flexlab

    - name: SSH into EC2 and run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/flexlab
          docker-compose down
          docker-compose up --build -d
        EOF
